# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-$(CONFIG_BQ2589X_CHARGER)   += bq2589x_chg_mmi/
obj-$(CONFIG_MMI_DISCRETE_CHARGER) += mmi_discrete_charger/
obj-$(CONFIG_MMI_CHARGER) += mmi_charger/
obj-$(CONFIG_MMI_DISCRETE_TURBO_CHARGER) += mmi_discrete_turbo_charger/

#ifdef OPLUS_FEATURE_CHG_BASIC
obj-$(CONFIG_OPLUS_SM8550_CHARGER)	+= oplus/
#endif
